SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `turmas` DEFAULT CHARACTER SET utf8mb4 ;
USE `turmas` ;

CREATE TABLE IF NOT EXISTS `turmas`.`contas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `professor` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `turmas`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `qnt_turmas` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `turmas`.`turmas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` FLOAT NOT NULL,
  `data_compra` DATE NOT NULL,
  `contas_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_turmas_contas_idx` (`contas_id` ASC),
  INDEX `fk_turmas_cursos1_idx` (`cursos_id` ASC),
  CONSTRAINT `fk_turmas_contas`
    FOREIGN KEY (`contas_id`)
    REFERENCES `turmas`.`contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `turmas`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
